### ISSUE TITLE
Bitwarden: error code: 1020

### ISSUE THREAD

**Issue by Aurelius-su** [detunized/password-manager-access#77]
RestClient.cs
142 var response = _http.SendAsync(request).GetAwaiter().GetResult();

Method: POST, RequestUri: 'https://vault.bitwarden.com/identity/connect/token'
response = {StatusCode: 403, ReasonPhrase: 'Forbidden'}
Content = "error code: 1020"

An uninformative error message also appears:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: e. Path '', line 0, position 0
 
password-manager-access v9.1.1 (NuGet package also)
bw.exe - OK!
Browser extensions - OK!
Firewall is OFF

A month ago everything worked without errors

**Comment by detunized** [comment]
This is most likely the Cloudflare anti-bot protection. Please try to login usi CLI API mode. You would need to get client ID/secret pair from the account settings. See [here](https://github.com/detunized/password-manager-access/blob/7f4094e875704543cb65a1eca07d80994074568c/src/Bitwarden/Vault.cs#L59)

```cs
// The main entry point. Use this function to open the vault in the CLI/API mode. In
// this mode the login is fully non-interactive even with 2FA enabled. Bitwarden servers
// don't use 2FA in this mode and permit to bypass it. There's no captcha in this mode
// either. If the browser mode is triggering a captcha, this mode should be used instead.
// This mode requires a different type of credentials that could be found in the vault
// settings: the client ID and the client secret.
// The device ID should be unique to each installation, but it should not be new on
// every run. A new random device ID should be generated with GenerateRandomDeviceId
// on the first run and reused later on.
public static Vault Open(ClientInfoCliApi clientInfo, string baseUrl = null)
{
    ...
```

**Comment by detunized** [comment]
If you still observer the issue, please reopen the ticket with more info.

**Comment by Aurelius-su** [comment]
Thanks for the tip. I have used ClientInfoCliApi.

**Comment by Aurelius-su** [comment]
Oops...

Vault vault = Vault.Open(new ClientInfoCliApi(...));

RestClient.cs
142 var response = _http.SendAsync(request).GetAwaiter().GetResult();

Method: POST, RequestUri: 'https://vault.bitwarden.com/identity/connect/token'

Fiddler inspector
	FormUrlEncodedContent:
		client_id: user.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
		client_secret: XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXx
		grant_type: client_credentials
		scope: api
		deviceType: 7
		deviceName: macos
		deviceIdentifier: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
	response = {StatusCode: 403, ReasonPhrase: 'Forbidden'}
	Server: cloudflare
	Content = "error code: 1020"

**Comment by detunized** [comment]
I tested with the CLI mode and I don't get this error on macOS. It's possible that it has something do do with your network configuration. If possible, try to login with [Bitwarden CLI](https://bitwarden.com/help/cli/) with the same credentials.

Another idea: if you're running Windows, try to replace 

```cs
deviceType: 7
deviceName: macos
```

with 

```cs
deviceType: 6
deviceName: windows
```

or with

```cs
deviceType: 8
deviceName: linux
```

if you're running Linux. The code is [here](https://github.com/detunized/password-manager-access/blob/7f4094e875704543cb65a1eca07d80994074568c/src/Bitwarden/Client.cs#L690)

**Comment by Aurelius-su** [comment]
Over time, the error got tired without my participation. I did not find out the reasons.
