### ISSUE TITLE
LastPass TOTP Seed

### ISSUE THREAD

**Issue by kspearrin** [detunized/password-manager-access#87]
In my enterprise LastPass test account I can add a TOTP seed to a Account item in my vault. I can also see this TOTP seed exported with my CSV from LastPass.

![image](https://user-images.githubusercontent.com/1190944/219760433-a7932582-0f7a-4c26-8804-2dfc0ddfcb36.png)

I would like to add it to the LastPass `Account` object here, but am having a hard time finding it in the LastPass parser. I have tried adding more `ReadItem()` calls instead of skipping (thinking one of the skip calls was skipping the TOTP), but I have not been able to locate a value that matches what I have stored in LastPass. Ex:

                var notes = Util.DecryptAes256Plain(ReadItem(reader), encryptionKey, placeholder);
                var favorite = ReadItem(reader).ToUtf8();
                // SkipItem(reader);

                // Looking for TOTP seed
                var maybeseed = Util.DecryptAes256Plain(ReadItem(reader), encryptionKey, placeholder);

                var username = Util.DecryptAes256Plain(ReadItem(reader), encryptionKey, placeholder);
                var password = Util.DecryptAes256Plain(ReadItem(reader), encryptionKey, placeholder);
                // SkipItem(reader);
                // SkipItem(reader);

                // Looking for TOTP seed
                var a = Util.DecryptAes256Plain(ReadItem(reader), encryptionKey, placeholder);
                var b = Util.DecryptAes256Plain(ReadItem(reader), encryptionKey, placeholder);
                var c = Util.DecryptAes256Plain(ReadItem(reader), encryptionKey, placeholder);
                var d = Util.DecryptAes256Plain(ReadItem(reader), encryptionKey, placeholder);
                var e = Util.DecryptAes256Plain(ReadItem(reader), encryptionKey, placeholder);
                var f = Util.DecryptAes256Plain(ReadItem(reader), encryptionKey, placeholder);

Any tips on how to locate this TOTP seed property in the LastPass payload?

**Comment by detunized** [comment]
It's possible that there's no room in this chunk for this and it's encoded elsewhere. Unfortunately I do not have an enterprise account to check. I sent you an email about this to the address from the git commit.
